name: 인프라/배포
description: 인프라 또는 배포 관련 작업
title: "[Infra] "
labels: ["infra"]
body:
  - type: markdown
    attributes:
      value: |
        인프라 또는 배포 관련 작업을 기록합니다.

  - type: dropdown
    id: type
    attributes:
      label: 작업 유형
      options:
        - 배포 설정
        - CI/CD 파이프라인
        - Docker 설정
        - 서버 설정
        - 모니터링
        - 기타
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      description: 어떤 작업을 진행하나요?
      placeholder: 작업 내용을 설명해 주세요
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 세부 작업 목록
      description: 진행할 세부 작업을 체크리스트로 작성해 주세요
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
        - [ ] 작업 3

  - type: textarea
    id: affected
    attributes:
      label: 영향 범위
      description: 이 작업으로 영향받는 시스템이나 서비스를 알려주세요
      placeholder: |
        - Backend 컨테이너
        - GitHub Actions

  - type: textarea
    id: reference
    attributes:
      label: 참고 자료
      description: 참고할 문서나 링크가 있다면 첨부해 주세요
