name: 일반 작업
description: 일반적인 개발 작업을 기록합니다
title: "[Task] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        개발 작업을 기록합니다.

  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      description: 어떤 작업을 진행하나요?
      placeholder: 작업 내용을 설명해 주세요
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 세부 작업 목록
      description: 진행할 세부 작업을 체크리스트로 작성해 주세요
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
        - [ ] 작업 3

  - type: textarea
    id: related
    attributes:
      label: 관련 파일/이슈
      description: 관련된 파일이나 이슈가 있다면 링크해 주세요
      placeholder: |
        - #123
        - src/pages/SomePage.jsx

  - type: textarea
    id: notes
    attributes:
      label: 참고 사항
      description: 추가로 참고할 내용이 있다면 작성해 주세요
